### ISSUE TITLE
docker로 tadpole 설치 후에 로그가 쌓이지 않는 현상에 대해 궁금합니다.

### ISSUE THREAD

**Issue by brendaniel** [hangum/TadpoleForDBTools#1001]
tadpole 자체 DB가 생성이 안 되서 오류가 발생하는 것 같은데, 해결방법이 있을까요?
로그 내용은 다음과 같습니다.

``` java
2017-08-16 01:51:00,765 ERROR [UIThread [24abdb59]] sqlaudit.AdminSQLAuditEditor (AdminSQLAuditEditor.java:539)     - Executed SQL History call
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/hangum/tadpole/engine/query/internal/system/Tadpole-System-Common.xml.  
--- The error occurred while executing query.  
--- Check the    SELECT      b.executed_sql_resource_seq,      a.types,     a.duration,     a.startdateexecute,      a.enddateexecute,     a.message,      b.datas,      a.row,      a.result,        u.email,        u.name,         db.display_name,         a.ipaddress,         db.seq as dbseq   FROM     executed_sql_resource a,    executed_sql_resource_data b,    tadpole_user u,    tadpole_db db  where 1=1          AND a.delyn = 'NO'     AND u.email like ?    AND a.seq = b.executed_sql_resource_seq     AND a.startdateexecute >= ?          AND a.enddateexecute <= ?        AND a.duration >= ?        AND a.user_seq = u.seq        AND b.datas like ?         AND a.db_seq = db.seq                            order by a.create_time   limit ?, ?  .  
--- Check the SQL Statement (preparation failed).  
--- Cause: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: executed_sql_resource)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94)
	at com.hangum.tadpole.engine.query.sql.TadpoleSystem_ExecutedSQL.getExecuteQueryHistoryDetail(TadpoleSystem_ExecutedSQL.java:113)
	at com.hangum.tadpole.engine.query.sql.TadpoleSystem_ExecutedSQL.getAllExecuteQueryHistoryDetail(TadpoleSystem_ExecutedSQL.java:64)
	at com.hangum.tadpole.commons.admin.core.editors.sqlaudit.AdminSQLAuditEditor.search(AdminSQLAuditEditor.java:503)
	at com.hangum.tadpole.commons.admin.core.editors.sqlaudit.AdminSQLAuditEditor.access$3(AdminSQLAuditEditor.java:474)
	at com.hangum.tadpole.commons.admin.core.editors.sqlaudit.AdminSQLAuditEditor$6.widgetSelected(AdminSQLAuditEditor.java:295)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:262)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:58)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: executed_sql_resource)
	at org.sqlite.DB.newSQLException(DB.java:383)
	at org.sqlite.DB.newSQLException(DB.java:387)
	at org.sqlite.DB.throwex(DB.java:374)
	at org.sqlite.NativeDB.prepare(Native Method)
	at org.sqlite.DB.prepare(DB.java:123)
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
	at org.sqlite.Conn.prepareStatement(Conn.java:404)
	at org.sqlite.Conn.prepareStatement(Conn.java:399)
	at org.sqlite.Conn.prepareStatement(Conn.java:383)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:541)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:219)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 30 more
2017-08-16 01:52:18,284 ERROR [UIThread [24abdb59]] realtime.MonitoringMainEditor (MonitoringMainEditor.java:193)     - get monitoring db list
com.ibatis.sqlmap.client.SqlMapException: There is no statement named getUserMonitoringDBList in this SqlMap.
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.getMappedStatement(SqlMapExecutorDelegate.java:231)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:558)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94)
	at com.hangum.tadpole.engine.query.sql.TadpoleSystem_monitoring.getUserMonitoringDBList(TadpoleSystem_monitoring.java:71)
	at com.hangum.tadpole.monitoring.core.editors.monitoring.realtime.MonitoringMainEditor.createPartControl(MonitoringMainEditor.java:177)
	at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:668)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:464)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:599)
	at org.eclipse.ui.internal.EditorReference.getEditor(EditorReference.java:286)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2858)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2763)
	at org.eclipse.ui.internal.WorkbenchPage.access$11(WorkbenchPage.java:2755)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:2706)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2702)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2686)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2669)
	at com.hangum.tadpole.monitoring.core.actions.monitoring.MonitoringRealTimeAction.run(MonitoringRealTimeAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:443)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:58)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

```

**Comment by hangum** [comment]
@brendaniel  쿼리의 로그가 쌓이는 기능은 엔터프라이즈 기능의 일부라 오픈소스에서는 지원되지 않습니다.
필요하시면 엔터프라이즈 버전을 이용해 주십시오. 

오픈소스에서는 해당 로그가 보이지않도록 개선해야겠네요.  오픈소스에서는 이슈를 만들고 개선할 수 있도록 하겠습니다. 
감사합니다.

**Comment by brendaniel** [comment]
@hangum 넵 추가적으로 궁금한게

DB 연결 정보를 영구적으로 가져가고싶은데, 어디에 저장되는지 알 수 있을까요?
Volumn 명령어로 그부분을 마운트 하고 싶어서요.

**Comment by hangum** [comment]
@brendaniel 엔터프라이즈 버전은 엔진디비를 mysql 을 사용하여서 원하시는것을 해결하고 있습니다. 
오픈소스는 sqlite 를 사용하고 있는데 web.xml 속성에 -dbPath /Users/hangum/engingdb 라고 주시면 엔진 파일이 해당 디렉토리에 생길 것입니다. 
-dbPath에 지정한 디렉토리를 공유 디렉토리로 지정하시면 되겠습니다. 

감사합니다.

**Comment by brendaniel** [comment]
@hangum 감사합니다. 
로그인 히스토리 기능도 엔터프라이즈 버전의 일부인가요?
(버전별 기능 구분이 되어있는 링크가 있다면 알려주시면 감사하겠습니다)

`Cause: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: login_history)`

**Comment by hangum** [comment]
@brendaniel  네 로그인 히스토리도 엔터중의 일부 입니다.
쉽게 생각하시면, 개인이 쓰시기에는 오픈소스 회사가 쓰기에는 엔터프라이즈로 생각하시면 되겠네요. 

다음 슬라이드를 참고하시면 도움이 되겠습니다.
https://www.slideshare.net/hangum/vs-65297864
