### ISSUE TITLE
버그 입니다.

### ISSUE THREAD

**Issue by ys2cdh** [hangum/TadpoleForDBTools#707]
안녕하세요. 
Tadpole DB Hub Version 1.6.8 SR Build(R0) 버전을 사용 하고 있습니다.

기능 중 모든 테이블 ERD로 만들기를 실행 하였더니 아래와 같은 에러가 나옵니다.
혹시 더필요한 정보가 있으시면 메일로 드리겠습니다.

감사합니다.

java.lang.Exception
	at com.hangum.tadpole.rdb.erd.core.editor.TadpoleRDBEditor$2$1.run(TadpoleRDBEditor.java:186)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:50)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

**Comment by hangum** [comment]
오류는 아마 스키마를 분석하는 중에 나타나는 것으로 생각됩니다. 

디비 종류와 해당 디비 스키마를 볼수 있으면 좋겠습니다. 
보내 주실수 있다면( hangum@gmail.com )으로 부탁드리겠습니다.

**Comment by hangum** [comment]
https://github.com/hangum/TadpoleForDBTools/issues/169
몇년전에도 비슷한 리포팅이 있었네요.
현재 테스트하고 가지고 있는 스키마에서는 리포팅하신 문제가 일어나고 있지 않아서, 실행했을때 오류가 나는 스키마가 필요합니다.

**Comment by hangum** [comment]
주말에 베타정도를 내 놓을텐데, 테스트 부탁드려요.
