### ISSUE TITLE
Blob컬럼이 포함된 쿼리 실행 후 그리드 스크롤시 오류 로그가 표시됩니다.

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleForDBTools#747]
Blob컬럼을 포함하는 테이블 쿼리 후 스크롤할때 다음 자료를 자동으로 불러오는 중에 다음과 같은 오류가 콘솔에 표시됩니다.

실제 사용자 UI에서는 오류 메시지가 표시된다거나 자료가 조회되지 않는 현상은 없으며 정상적으로 조회되고 있습니다.

--------이클립스 콘솔 로그 내용------
2016 4월 11 15:59:18, 270 ERROR - ResultSetUtils : getResultToList ResutSet fetch error 
java.sql.SQLException: 부적합한 열 유형: getString not implemented for class oracle.jdbc.driver.T4CBlobAccessor
	at oracle.jdbc.driver.Accessor.unimpl(Accessor.java:414)
	at oracle.jdbc.driver.BlobAccessor.getString(BlobAccessor.java:335)
	at oracle.jdbc.driver.OracleResultSetImpl.getString(OracleResultSetImpl.java:1297)
	at org.apache.commons.dbcp.DelegatingResultSet.getString(DelegatingResultSet.java:213)
	at org.apache.commons.dbcp.DelegatingResultSet.getString(DelegatingResultSet.java:213)
	at com.hangum.tadpole.engine.sql.util.resultset.ResultSetUtils.getResultToList(ResultSetUtils.java:88)
	at com.hangum.tadpole.engine.sql.util.resultset.ResultSetUtilDTO.<init>(ResultSetUtilDTO.java:115)
	at com.hangum.tadpole.engine.sql.util.resultset.QueryExecuteResultDTO.<init>(QueryExecuteResultDTO.java:39)
	at com.hangum.tadpole.rdb.core.editors.main.composite.ResultSetComposite.runSelect(ResultSetComposite.java:537)
	at com.hangum.tadpole.rdb.core.editors.main.composite.resultdetail.ResultTableComposite.calcTableData(ResultTableComposite.java:474)
	at com.hangum.tadpole.rdb.core.editors.main.composite.resultdetail.ResultTableComposite.access$1(ResultTableComposite.java:452)
	at com.hangum.tadpole.rdb.core.editors.main.composite.resultdetail.ResultTableComposite$3.handleEvent(ResultTableComposite.java:187)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:50)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
15:59:18, 272 DEBUG - ResultTableComposite:calcTableData ==> old count is 2000 
2016 4월 11 15:59:18, 272 DEBUG - ResultTableComposite : calcTableData ==> old count is 2000

**Comment by jeongjaehong** [comment]
500건과 501건에서 각각 "행결과 자세히 보기" 팝업메뉴를 클릭했을때... 500번째 이하 행에서는 에러가 없음.

501건 이상의 행에서는 첨부와 같은 오류가 발생함.

![capture 19](https://cloud.githubusercontent.com/assets/859932/14419297/d76f9190-ffff-11e5-80ad-d16251ad9087.png)

![capture 18](https://cloud.githubusercontent.com/assets/859932/14419280/b4e4d91e-ffff-11e5-868c-2913967a1b32.png)

**Comment by hangum** [comment]
blob 에러와 데이터 500건 넘어가는 오류는 오전중에 수정할게요.

**Comment by jeongjaehong** [comment]
Blob 데이터를 그리드에 다 넣어두거나...다음자료 스크롤때도 마찬가지고 그리드에 로딩하는건 상당히 무리가 될수도 있을듯한데요? 

export할때도 그렇고.. 

blob데이터의 특성(이미지, 텍스트, 바이너리..., xml) 에 따라서 뭔가 적절한 방법을 찾와봐야 할듯 합니다.

오라클 Blob, Clob, Long 데이터 타입이나 다른 dbms의 대용량 데이터 저장을 위한 컬럼들에 대한 고민이 필요할것 같습니다. 

코드
					if(obj instanceof Blob) {
						tmpRow.put(intShowColIndex, rs.getObject(intColIndex));
					} else {
						tmpRow.put(intShowColIndex, rs.getString(intColIndex));
					}

로그내용
2016 4월 12 08:49:18, 511 DEBUG - ResultSetUtils : getResultToList ======[jdbc type ]===> 2004, class type is oracle.sql.BLOB

**Comment by jeongjaehong** [comment]
컬럼보기를 할때 이미지의 경우 바로 보기를 할수 있도록 되어 있긴한데.. 일단 export에서는 제외시키는게 맞을듯하고 key컬럼을 이용하여 파일명으로 사용하고 blob내용을 지정된 폴더에 파일로 생성해 주는 export 기능이 있으면 편리하긴 하겠네요..

**Comment by hangum** [comment]
우선 위의 두개의 오류는 수정할게요. 
수정 사항은  blob 타입이 올챙이에서 잘못 정의 되는 오류를 수정했어요. 

export는 형이 정리를 하겠어요.
