### ISSUE TITLE
' no layout registered with default id'  exception occurs 

### ISSUE THREAD

**Issue by sunhanintech** [hangum/TadpoleForDBTools#840]
오늘자 Fetch 받아 실행하니.. 아래의 오류가 나내요... 

----

2016 Jun 20 13:56:03, 892 INFO - TadpoleSystemInitializer : initJDBCDriver ######### TDB JDBC Driver local Path : /home/mimi/tadpole/driver/ 

!ENTRY org.eclipse.rap.ui 4 0 2016-06-20 13:56:04.764
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: no layout registered with default id (LayoutRegistry.DEFAULT_LAYOUT_ID) or no layout activated over branding extension.
	at org.eclipse.rap.ui.interactiondesign.layout.ElementBuilder.<init>(ElementBuilder.java:96)
	at org.eclipse.rap.internal.design.example.builder.DummyBuilder.<init>(DummyBuilder.java:24)
	at org.eclipse.rap.internal.design.example.managers.CoolBarManager.<init>(CoolBarManager.java:143)
	at org.eclipse.rap.internal.design.example.business.BusinessPresentationFactory.createCoolBarManager(BusinessPresentationFactory.java:32)
	at org.eclipse.ui.internal.WorkbenchWindow.createCoolBarManager2(WorkbenchWindow.java:3991)
	at org.eclipse.jface.window.ApplicationWindow.addCoolBar(ApplicationWindow.java:288)
	at org.eclipse.ui.internal.WorkbenchWindow.<init>(WorkbenchWindow.java:391)
	at org.eclipse.ui.internal.tweaklets.Workbench3xImplementation.createWorkbenchWindow(Workbench3xImplementation.java:29)
	at org.eclipse.ui.internal.Workbench.newWorkbenchWindow(Workbench.java:1933)
	at org.eclipse.ui.internal.Workbench.access$11(Workbench.java:1931)
	at org.eclipse.ui.internal.Workbench$16.runWithException(Workbench.java:1244)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:32)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:230)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:1092)
	at org.eclipse.ui.internal.StartupThreading.runWithWorkbenchExceptions(StartupThreading.java:55)
	at org.eclipse.ui.internal.Workbench.busyOpenWorkbenchWindow(Workbench.java:1242)
	at org.eclipse.ui.internal.Workbench.doOpenFirstTimeWindow(Workbench.java:2061)
	at org.eclipse.ui.internal.Workbench.openFirstTimeWindow(Workbench.java:1992)
	at org.eclipse.ui.internal.WorkbenchConfigurer.openFirstTimeWindow(WorkbenchConfigurer.java:188)
	at org.eclipse.ui.application.WorkbenchAdvisor.openWindows(WorkbenchAdvisor.java:790)
	at org.eclipse.ui.internal.Workbench$27.runWithException(Workbench.java:1640)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:32)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:230)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:1092)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:110)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1635)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2655)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:48)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

**Comment by hangum** [comment]
@iamsunhan  이 에러는 올챙이에서 사용하는 Business theme를 못찾은(?) 오류로 보이구요. 
Business theme는 라이브러리에 있는 코드라서 딱히 뭔가 건드리거나 하지 않는 이상 오류가 나지 않는데 이상하네요. 

메뉴 -> Project -> clean 을 실행하고 실행해보시겠어요. 
오류가 나면 이야기 해주세요.

**Comment by iamsunhan** [comment]
움.. 그정도는 이미..다 해봤죵.. ㅎㅎ 
클린빌드 하고.... 안되서 ..에러메시지 확인해보고 소스 가보고....... 까지는 해용... 
암튼.. 오늘자 버전도 여전히 .. 동일에러 발생하네요...

**Comment by hangum** [comment]
음 격어보지 못해서, 어떻게 해야할지 모르겠네요. 
가장 쉽게 해볼수 있는 것은 Add required Bundles 를 눌러보시고, validate bundles 을 눌러보세요. 

![image](https://cloud.githubusercontent.com/assets/1335915/16217204/28cc4f9a-37ac-11e6-953b-a46a7c803f17.png)
