### ISSUE TITLE
PostGreSQL 펑션 DDL 문 조회 불가..

### ISSUE THREAD

**Issue by hyunmoo** [hangum/TadpoleForDBTools#860]
안녕하십니까 이번에 TadpoleForDBTools 알게되어 한번 테스트 사용중에 나온 버그를 알려드리고자 글을 남깁니다.

접속 
DB는 PostGreSQL  이며 버전은 9.5 버전입니다.

실행환경은 Windows10 64비트 입니다.

브라우저와 TadpoleForDBTools 32비트, 64비트 관계없이

PostGreSQL  db의 펑션 항목의 ddl 문 보기가 되지 않습니다.

에러창이 나타납니다만, 에러 메세지가 출력되지 않습니다.

**Comment by hangum** [comment]
에러로그는 독립 실행 모듈의 경우 설치폴더 아래 logs/ 아래에 저장되고 있을싯듯합니다. 
톰켓의 경우 bin/logs 디렉토리 또는 logs 입니다.

보내주시면 에러로그 파악하기 좀더 쉽겠습니다. 

감사합니다.

**Comment by hyunmoo** [comment]
펑션의 DDL문 보기시 에러 구문입니다.

2016-07-20 15:31:29,878 INFO  [UIThread [5f9e498]] initialize.TadpoleSystemInitializer (TadpoleSystemInitializer.java:146)     - ######### TDB JDBC Driver local Path : C:\Users\winte\tadpole\driver\
2016-07-20 15:31:51,033 ERROR [UIThread [5f9e498]] generate.GenerateViewDDLAction (GenerateViewDDLAction.java:109)     - view ddl
java.lang.NullPointerException
	at com.hangum.tadpole.engine.sql.util.sqlscripts.scripts.PostgreSQLDDLScript.getFunctionScript(PostgreSQLDDLScript.java:225)
	at com.hangum.tadpole.engine.sql.util.sqlscripts.scripts.PostgreSQLDDLScript.getFunctionScript(PostgreSQLDDLScript.java:213)
	at com.hangum.tadpole.engine.sql.util.sqlscripts.DDLScriptManager.getScript(DDLScriptManager.java:132)
	at com.hangum.tadpole.rdb.core.actions.object.rdb.generate.GenerateViewDDLAction.run(GenerateViewDDLAction.java:103)
	at com.hangum.tadpole.rdb.core.actions.object.AbstractObjectAction.run(AbstractObjectAction.java:208)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:48)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)


추가로 테이블 데이터 직접 수정시에도 에러가 나옵니다...

org.postgresql.util.PSQLException: ERROR: relation "test.test_table" does not exist
  Position: 99
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:616)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:466)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:351)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.runSQLSelect(TableDirectEditorComposite.java:402)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.initBusiness(TableDirectEditorComposite.java:334)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.<init>(TableDirectEditorComposite.java:309)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableInformationEditor.createPartControl(TableInformationEditor.java:111)
	at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:668)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:464)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:599)
	at org.eclipse.ui.internal.PartPane.setVisible(PartPane.java:310)
	at org.eclipse.ui.internal.presentations.PresentablePart.setVisible(PresentablePart.java:185)
	at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(PresentablePartFolder.java:265)
	at org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRightTabOrder.java:64)
	at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(TabbedStackPresentation.java:479)
	at org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:1262)
	at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1215)
	at org.eclipse.ui.internal.PartStack.showPart(PartStack.java:1614)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:508)
	at org.eclipse.ui.internal.EditorStack.add(EditorStack.java:106)
	at org.eclipse.ui.internal.PartStack.add(PartStack.java:494)
	at org.eclipse.ui.internal.EditorStack.add(EditorStack.java:115)
	at org.eclipse.ui.internal.EditorSashContainer.addEditor(EditorSashContainer.java:65)
	at org.eclipse.ui.internal.EditorAreaHelper.addToLayout(EditorAreaHelper.java:225)
	at org.eclipse.ui.internal.EditorAreaHelper.addEditor(EditorAreaHelper.java:213)
	at org.eclipse.ui.internal.EditorManager.createEditorTab(EditorManager.java:775)
	at org.eclipse.ui.internal.EditorManager.openEditorFromDescriptor(EditorManager.java:673)
	at org.eclipse.ui.internal.EditorManager.openEditor(EditorManager.java:633)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2855)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2763)
	at org.eclipse.ui.internal.WorkbenchPage.access$11(WorkbenchPage.java:2755)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:2706)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2702)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2686)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2677)
	at com.hangum.tadpole.rdb.core.actions.object.rdb.TableDataEditorAction.run(TableDataEditorAction.java:107)
	at com.hangum.tadpole.rdb.core.actions.object.AbstractObjectAction.run(AbstractObjectAction.java:208)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:48)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

감사합니다.

**Comment by hyunmoo** [comment]
2016-07-20 15:39:44,102 INFO  [UIThread [26173099]] initialize.TadpoleSystemInitializer (TadpoleSystemInitializer.java:146)     - ######### TDB JDBC Driver local Path : C:\Users\winte\tadpole\driver\
2016-07-20 15:39:44,102 INFO  [UIThread [26173099]] initialize.TadpoleSystemInitializer (TadpoleSystemInitializer.java:148)     - 	##### Copying initialize JDBC Driver........
2016-07-20 15:39:44,102 INFO  [UIThread [26173099]] initialize.TadpoleSystemInitializer (TadpoleSystemInitializer.java:154)     - ##### TDB JDBC URI: C:\Users\winte\Desktop\win32.win32.x86_64\win32.win32.x86_64\TadpoleDBHub\plugins\com.hangum.tadpole.engine_1.0.0/libs/driver
2016-07-20 15:39:44,318 INFO  [UIThread [26173099]] initialize.TadpoleSystemInitializer (TadpoleSystemInitializer.java:120)     - Createion Engine DB. Type is SQLite.
2016-07-20 15:39:48,608 INFO  [UIThread [26173099]] application.Application (Application.java:60)     - Initialize System default setting.
2016-07-20 15:40:37,416 ERROR [UIThread [26173099]] generate.GenerateViewDDLAction (GenerateViewDDLAction.java:109)     - view ddl
java.lang.NullPointerException
	at com.hangum.tadpole.engine.sql.util.sqlscripts.scripts.PostgreSQLDDLScript.getFunctionScript(PostgreSQLDDLScript.java:225)
	at com.hangum.tadpole.engine.sql.util.sqlscripts.scripts.PostgreSQLDDLScript.getFunctionScript(PostgreSQLDDLScript.java:213)
	at com.hangum.tadpole.engine.sql.util.sqlscripts.DDLScriptManager.getScript(DDLScriptManager.java:132)
	at com.hangum.tadpole.rdb.core.actions.object.rdb.generate.GenerateViewDDLAction.run(GenerateViewDDLAction.java:103)
	at com.hangum.tadpole.rdb.core.actions.object.AbstractObjectAction.run(AbstractObjectAction.java:208)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:48)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
2016-07-20 15:40:42,294 ERROR [UIThread [26173099]] table.TableDirectEditorComposite (TableDirectEditorComposite.java:351)     - Data moidfying..
org.postgresql.util.PSQLException: ERROR: relation "sgpmes.cis_auth_grp" does not exist
  Position: 99
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:616)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:466)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:351)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.runSQLSelect(TableDirectEditorComposite.java:402)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.initBusiness(TableDirectEditorComposite.java:334)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableDirectEditorComposite.<init>(TableDirectEditorComposite.java:309)
	at com.hangum.tadpole.rdb.core.editors.objects.table.TableInformationEditor.createPartControl(TableInformationEditor.java:111)
	at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:668)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:464)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:599)
	at org.eclipse.ui.internal.EditorReference.getEditor(EditorReference.java:286)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditorBatched(WorkbenchPage.java:2858)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:2763)
	at org.eclipse.ui.internal.WorkbenchPage.access$11(WorkbenchPage.java:2755)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:2706)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2702)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2686)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:2677)
	at com.hangum.tadpole.rdb.core.actions.object.rdb.TableDataEditorAction.run(TableDataEditorAction.java:107)
	at com.hangum.tadpole.rdb.core.actions.object.AbstractObjectAction.run(AbstractObjectAction.java:208)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:48)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)


펑션 DDL 문 보기 및 테이블 데이터 직접 수정 시 에러 로그 2...

**Comment by hangum** [comment]
@hyunmoo 감사합니다. 확인해 보겠습니다.

**Comment by hangum** [comment]
@hyunmoo  사용하시는 Tadpole DB Hub 버전은 어떻게 되시는지요? 
최신 버전의 로그와 많이 틀려서 질문 드립니다.

**Comment by hyunmoo** [comment]
https://sourceforge.net/projects/tadpoledbhub/files/1.7.x/1.7.2/

1.7.3 버전은 독립 실행형 파일이 없어서 1.7.2 버전을 사용했습니다.

win32.win32.x86_64.zip 파일을 다운받아 실행했습니다.

**Comment by hangum** [comment]
아네. 
테스트 한 pgsql은 9.4.1 인데요. 9.5를 인스톨하고  테스트 해보겠습니다.

**Comment by hangum** [comment]
@hyunmoo  안녕하세요 
PGSQL : 9.5.3 버전을 인스톨하고 테스트 해보니 말하신 기능 모두 동작합니다. 
TadpoleDBHub : 1.7.2 r0 

테스트 케이스가 간단하여서 그럴수 있는데요. 
테스트할수 있는 셈플 데이터등을 받아 볼수 있을까요?

![image](https://cloud.githubusercontent.com/assets/1335915/17009390/0aae1f0c-4f35-11e6-969f-378fc71ce46d.png)
![image](https://cloud.githubusercontent.com/assets/1335915/17009406/278624e4-4f35-11e6-8653-669e38064e5b.png)
