### ISSUE TITLE
login problem with special charaters in password

### ISSUE THREAD

**Issue by iwizkr** [hangum/TadpoleForDBTools#961]
SQL Server 비밀번호에 특정 특수기호가 있는 경우 로그인 에러가 나는 것 같습니다.
어떤 문자가 문제인지 모르겠지만, 비밀번호에 포함된 특수문자는 = ` * ]  입니다.

**Comment by hangum** [comment]
사용하고 계시는 Sql server 보전은 어떻게 되시는 지요?

나의 iPhone에서 보냄

2017. 3. 15. 오후 2:28 iwizkr <notifications@github.com> 작성:

**Comment by iwizkr** [comment]
2008 r2 버전입니다.

**Comment by hangum** [comment]
독립 실행형 모듈을 쓰시면 logs/tadpole.log 나
톰켓 실행 환경이시면 bin/logs/tadpole.log  를 부탁드리겠습니다.

혹시 정보 공개가 걱정되시면 hangum@tadpolehub.com 으로 부탁드려요.

**Comment by iwizkr** [comment]
로그내용은 아래와 같습니다.
IP, DB명, username 등은 보안때문에 임의로 변경했습니다.

2017-03-15 16:01:31,239 ERROR [UIThread [40ab4e47]] manager.TadpoleSQLManager (TadpoleSQLManager.java:138)     - ***** get DB Instance seq is -999

org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Login failed for user 'msdbuser'.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.hangum.tadpole.engine.manager.TadpoleSQLManager.getInstance(TadpoleSQLManager.java:128)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.checkDatabase(AbstractLoginComposite.java:325)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.isValidateDatabase(AbstractLoginComposite.java:254)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.testConnection(AbstractLoginComposite.java:226)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.DBLoginDialog.buttonPressed(DBLoginDialog.java:281)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:609)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:262)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at com.hangum.tadpole.rdb.core.actions.global.ConnectDatabaseAction.runConnectionDialog(ConnectDatabaseAction.java:74)
	at com.hangum.tadpole.rdb.core.actions.global.ConnectDatabaseAction.run(ConnectDatabaseAction.java:57)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:443)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:56)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.sql.SQLException: Login failed for user 'msdbuser'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:632)
	at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:371)
	at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 43 more
2017-03-15 16:01:31,240 ERROR [UIThread [40ab4e47]] composite.AbstractLoginComposite (AbstractLoginComposite.java:334)     - DB Connecting... [url]jdbc:jtds:sqlserver://127.0.0.1:1433/mydb
com.hangum.tadpole.commons.exception.TadpoleSQLManagerException: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Login failed for user 'msdbuser'.)
	at com.hangum.tadpole.engine.manager.TadpoleSQLManager.getInstance(TadpoleSQLManager.java:142)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.checkDatabase(AbstractLoginComposite.java:325)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.isValidateDatabase(AbstractLoginComposite.java:254)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.composite.AbstractLoginComposite.testConnection(AbstractLoginComposite.java:226)
	at com.hangum.tadpole.rdb.core.dialog.dbconnect.DBLoginDialog.buttonPressed(DBLoginDialog.java:281)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:609)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:262)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:869)
	at org.eclipse.jface.window.Window.open(Window.java:845)
	at com.hangum.tadpole.rdb.core.actions.global.ConnectDatabaseAction.runConnectionDialog(ConnectDatabaseAction.java:74)
	at com.hangum.tadpole.rdb.core.actions.global.ConnectDatabaseAction.run(ConnectDatabaseAction.java:57)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:443)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1212)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1193)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2733)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2694)
	at org.eclipse.ui.internal.Workbench.access$5(Workbench.java:2530)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:701)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:684)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:157)
	at com.hangum.tadpole.application.Application.createUI(Application.java:56)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Login failed for user 'msdbuser'.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.hangum.tadpole.engine.manager.TadpoleSQLManager.getInstance(TadpoleSQLManager.java:128)
	... 40 more
Caused by: java.sql.SQLException: Login failed for user 'msdbuser'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:632)
	at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:371)
	at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 43 more

**Comment by hangum** [comment]
@jeongjaehong  형 테스트해주세요.
@iwizkr 패스워드관리 로직은 테스트 결과 이상이 없어 보입니다. 
디비 설정등을 살펴봐야지 싶습니다. 
http://stackoverflow.com/questions/17372606/sqlserver-login-failed-for-user

혹시 패스워드가 간단하면 정상 로그인이 되시는지요?

**Comment by iwizkr** [comment]
제가 DB 비밀번호를 변경할 권한을 가지고 있지 않아 단순 비밀번호는 모르겠습니다.
Linux-PHP나 JRun기반의 ColdFusion, Java기반의 Elastic Search에서도 사용하고 있는 데이터베이스라서 링크걸어주신 글의 Windows Authentication과는 관련이 없을 듯 합니다.
아무튼 신경써주신데 감사드리고, 제가 방법을 찾아보겠습니다.
좋은 프로그램을 만들어주셔서 고맙습니다.

**Comment by hangum** [comment]
@iwizkr  테스트환경을 만들어 해보겠습니다.

**Comment by hangum** [comment]
@iwizkr 문제가 되는 부분을 확인했습니다.  다음 버전 릴리즈 때 수정될수 있도록 하겠습니다.

**Comment by iwizkr** [comment]
고맙습니다. 다음 릴리즈가 기대되는군요.

**Comment by hangum** [comment]
코드 패치는 끝났습니다.  감사합니다.
